name: jump_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_drawing: ^1.0.1
  syncfusion_flutter_core: ^25.1.35
  syncfusion_flutter_sliders: ^25.1.35
  syncfusion_flutter_gauges: ^25.1.35
  provider: ^6.0.5
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_s2mJUMP_RGB.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/logo_s2mJUMP_RGB.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_s2mJUMP_RGB.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/key_frames_axel5.png
    - assets/images/key_frames_lutz4.png
    - assets/images/key_frames_back_somersault4.png
    - assets/images/biomech_model_translation.png   
    - assets/images/modele_biomeca_translation.png    
    - assets/images/biomech_model_rotation.png   
    - assets/images/modele_biomeca_rotation.png
    - assets/images/Logo_S2M_Patinage.png